version: '2'
services:
      gpsi_erp_db:
            image: postgres:9.4.7
            container_name: gpsi-demo-erp-db
            ports:
                  - "5432"
            environment:
                  - POSTGRES_USER=odoo
                  - POSTGRES_PASSWORD=odoo
      gpsi_erp:
            image: odoo:10
            container_name: gpsi-demo-erp
            volumes:
                  - ./src:/mnt/extra-addons
            ports:
                  - "8099:8069"
            environment:
                  - DB_PORT_5432_TCP_ADDR=gpsi_erp_db
                  - DB_PORT_5432_TCP_PORT=5432
                  - DB_ENV_POSTGRES_USER=odoo
                  - DB_ENV_POSTGRES_PASSWORD=odoo
            depends_on:
                  - gpsi_erp_db
